export const TYPES = {
    // Auth reducer types
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_UNSUCCESS: "LOGIN_UNSUCCESS",
    LOGOUT: "LOGOUT",
    RESET_ERROR: "RESET_ERROR",
    SET_FIRST_TIME_FALSE: "SET_FIRST_TIME_FALSE",
    REFRESH_PAGE: "REFRESH_PAGE",
    CHANGE_USERNAME: "CHANGE_USERNAME",
    CHANGE_EMAIL: "CHANGE_EMAIL",
}
